global:
  edition: ce
  hosts:
    domain: 127.0.0.1.nip.io
    https: false
  ingress:
    enabled: true
    configureCertmanager: false
    class: traefik
    annotations:
      kubernetes.io/ingress.class: "traefik"
  gatewayApi:
    enabled: false

  initialRootPassword:
    secret: gitlab-root-password
    key: password

  psql:
    host: gitlab-rails-db-rw.gitlab.svc.cluster.local
    port: 5432
    database: gitlabhq_production
    username: gitlab
    password:
      secret: gitlab-rails-db-app
      key: password

  redis:
    host: valkey.gitlab.svc.cluster.local
    port: 6379
    auth:
      secret: valkey-auth
      key: default-password

  appConfig:
    object_store:
      enabled: true
      proxy_download: true
      connection:
        secret: gitlab-object-storage
        key: config
      objects:
        artifacts:
          bucket: gitlab-artifacts
        lfs:
          bucket: git-lfs
        uploads:
          bucket: gitlab-uploads
        packages:
          bucket: gitlab-packages
        externalDiffs:
          bucket: gitlab-mr-diffs
        terraformState:
          bucket: gitlab-terraform-state
        ciSecureFiles:
          bucket: gitlab-ci-secure-files
        agentPlanContent:
          bucket: gitlab-agent-plan-content
        dependencyProxy:
          bucket: gitlab-dependency-proxy

certmanager-issuer:
  email: admin@local.dev
installCertmanager: false

# Disable heavy, non-essential components
prometheus:
  install: false
gitlab-runner:
  install: false

registry:
  enabled: false
  storage:
    secret: gitlab-registry-storage
    key: config
    redirect:
      disable: true

# Scale down critical components to 1 replica
gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        memory: 1.5G
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        memory: 1G
  toolbox:
    backups:
      objectStorage:
        config:
          secret: gitlab-object-storage-s3cmd
          key: config

# Disable bundled nginx
nginx-ingress:
  enabled: false
