BOX = "debian/bookworm64"
BOX_VERSION = "12.20250126.1"
SERVER_NAME = "smargineS"
SERVER_IP = "192.168.56.110"

Vagrant.configure("2") do |config|
  config.vm.box = BOX
  config.vm.box_version = BOX_VERSION

  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = "1024"
    libvirt.cpus = 1
    libvirt.nested = true
    libvirt.uri = "qemu:///system"
  end

  config.vm.define SERVER_NAME do |server|
    server.vm.hostname = SERVER_NAME
    server.vm.network :private_network, :ip => SERVER_IP

    server.vm.provision "shell", privileged: true, path: "scripts/server_setup.sh", env: {
      "SERVER_IP" => SERVER_IP
    }
  end
end
