BOX = "debian/bookworm64"
BOX_VERSION = "12.20250126.1"
SERVER_NAME = "mcuturaS"
WORKER_NAME = "mcuturaSW"
SERVER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"

Vagrant.configure("2") do |config|
  config.vm.box = BOX
  config.vm.box_version = BOX_VERSION
  config.vm.synced_folder ".", "/vagrant", type: "virtiofs"

  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = "1024"
    libvirt.cpus = 1
    libvirt.nested = true
    libvirt.uri = "qemu:///system"
    libvirt.memorybacking :access, :mode => "shared"
  end

  config.vm.define SERVER_NAME do |server|
    server.vm.hostname = SERVER_NAME
    server.vm.network :private_network, :ip => SERVER_IP

    server.vm.provision "shell", privileged: true, path: "scripts/server_setup.sh", env: {
      "SERVER_IP" => SERVER_IP
    }
  end

  config.vm.define WORKER_NAME do |worker|
    worker.vm.hostname = WORKER_NAME
    worker.vm.network :private_network, :ip => WORKER_IP

    worker.vm.provision "shell", privileged: true, path: "scripts/worker_setup.sh", env: {
      "SERVER_IP" => SERVER_IP,
      "WORKER_IP" => WORKER_IP
    }
  end
end
